version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: proyecto-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: proyecto
      POSTGRES_USER: proyectouser
      POSTGRES_PASSWORD: 09081999
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: proyecto-app
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: proyectouser
      DB_PASSWORD: 09081999
      DB_NAME: proyecto
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["/wait-for-it.sh", "postgres:5432", "--"]
    command: ["python3", "DB/genere_table_Postgres.py"]

volumes:
  postgres_data:

