# docker-compose.yml
version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: proyecto-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: proyecto
      POSTGRES_USER: proyectouser
      POSTGRES_PASSWORD: 09081999
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
